FROM gitpod/workspace-full:latest

USER root
# Installing Tools
# - silversearcher-ag
RUN apt-get update && apt-get install -y \
  silversearcher-ag \
  && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
# - bat
RUN wget https://github.com/sharkdp/bat/releases/download/v0.11.0/bat_0.11.0_amd64.deb
RUN dpkg -i bat_0.11.0_amd64.deb

USER gitpod
ENV WORKSPACE /workspace/practise_coding
RUN echo "WORKSPACE_ROOT=$WORKSPACE" >> ~/.bashrc
RUN echo "cd \$WORKSPACE_ROOT/src/bash_configs; source bashrc_standard.sh; cd -" >> ~/.bashrc
RUN git config --include --global include.path $WORKSPACE/src/git_configs/gitconfig_standard

RUN pip3 install numpy
RUN pip3 install sympy
RUN pip3 install matplotlib

# Give back control
USER root